apiVersion: v1
kind: ConfigMap
metadata:
  name: cnt-qa
data:
  DBA_URL: "https://database.com/utrain/qa"
  PORT_NUMBER: "8080"
  MONITOR_URL: "https://prometheus.com/qa"
  WEB_CONTENT: "/opt/qa/content"
  WEB_VOLUME: "qa-volumes"